name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
    - name: Install dependencies
      uses: bahmutov/npm-install@v1
    - name: Add node_modules/.bin to PATH
      run: |
        echo "./node_modules/.bin/" >> $GITHUB_PATH
    - name: Run tests
      run: elm-test
    - name: Verify formatting
      run: elm-format src --validate
    - name: Build the application
      run: elm make src/Main.elm
